#
###################################
# Site wide configuration
####################################
#
title: TheMeanTime
email: eugene@debeste.co.za
description: A Blog About My Personal Experiences in Tech
url: https://themeanti.me
keywords: ["blog", "jekyll", "tech", "programming", "devops"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Africa/Johannesburg
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /:categories/:year/:month/:day/:title.html

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: TheMeanTi.me
  avatar: eugene_de_beste_small.jpg
  job: "Eugene de Beste"
  bio: "A Blog About My Personal Experiences in Tech."
  email: eugene@debeste.co.za
  disqus-shortname:
  twitter: edebeste
  facebook: #
  google:
    plus: #username
    analytics: UA-115666618-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Banshee1221
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: eugene-de-beste
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
