---

version: '3'

services:
  hugo:
    image: ghcr.io/hugomods/hugo:0.123.7@sha256:f4824bbc4a940a1f96db6a092bc6bb3fd1828d2428ace03e4a9322236a2bf49c
    volumes:
      - ./:/src
    ports:
      - '1313:1313'
    command: hugo server --bind 0.0.0.0 -D --poll 700ms